name: publish
on:
    push:
        branches:
            - source

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip run')"

        steps:
            - uses: actions/checkout@v2
              with:
                submodules: true

            - uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: "latest"
                extended: true

            - name: build pages
              run: hugo

            - name: push
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
                publish_branch: master