name: publish
on:
    push:
        branches:
            - source

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'skip run')"

        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true

            - uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: "latest"
                extended: true

            - uses: actions/setup-node@v4
              with:
                node-version: 18
              
            - name: install dependencies
              run: npm install -g postcss postcss-cli autoprefixer

            - name: build
              run: hugo --minify

            - name: push
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./public
                publish_branch: master
                cname: hataya.tokyo